service: bot-framework

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
  iamRoleStatements:
      -  ${file(policies/dynamo.db.json)}

functions:
  input:
    handler: handler.input
    memorySize: 128
    events:
      - http:
          path: input
          method: post
