service: bot-framework

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
  iamRoleStatements:
      - ${file(policies/dynamo.db.json)}
      - ${file(policies/lambda.json)}

functions:

  input:
    handler: handler.input
    memorySize: 128
    events:
      - http:
          path: input
          method: post
      - sns:
          topicName: bot-framework-input
          displayName: Bot framework input handler

  addPrinter:
    handler: handler.addPrinter
    memorySize: 128
    events:
      - http:
          path: printer
          method: post

  addUser:
    handler: handler.addUser
    memorySize: 128
    events:
      - http:
          path: user
          method: post

  addGroup:
    handler: handler.addGroup
    memorySize: 128
    events:
      - http:
          path: group
          method: post
